#!/usr/bin/env bash

bash --version | head -n1 | sed 's/GNU bash, version \([0-9]\+\.[0-9]\+\.[0-9]\+\).*/bash \1/'
tmux -V
vim --version | head -n1 | sed 's/VIM - Vi IMproved \([0-9]\+\.[0-9]\+\).*/vim \1/'
git --version | sed -e 's/ version//'
python --version
python3 --version
